[postgresql]
# Эти данные теперь в .env
host = ${DB_HOST}
database = ${DB_NAME}
user = ${DB_USER}
password = ${DB_PASS}
port = ${DB_PORT}

[window]
width = 820
height = 600
title = TeragisPulse

[table_main]
col_width = 115
row_height = 30
header_font_size = 13
cell_font_size = 18

[table_clients]
col_width = 200
row_height = 30
header_font_size = 12
cell_font_size = 12
max_chars_fio = 25
max_chars_comment = 45

[status_colors]
Completed = #ff8e8a
On_Treatment = #66ff66

[colors]
Planned_1 = #E0FFFF
Completed_1 = #AFEEEE
Total_1 = #7FFFD4
Planned_2 = #ccff99
Completed_2 = #b3ff66
Total_2 = #99ff33
Planned_Other = #FFFACD
Completed_Other = #EEE8AA
Total_Other = #FFD700
Planned_All = #E6E6FA
Completed_All = #D8BFD8
Total_All = #DDA0DD
Default = #ffffff

[telegram]
use_ws = True
interval_minutes = 0
interval_seconds = 5
max_hours = 0
no_change_minutes = 30

[db]
# Устаревший блок, данные теперь в .env